services:
  - type: web
    name: hairgo-backend
    env: node
    plan: free
    buildCommand: yarn ci --production
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromDatabase:
          name: hairgo-db
          property: connectionString
        key: DATABASE_URL

databases:
  - name: hairgo-db
    plan: free
    databaseName: hairgo
    user: hairgo_user
